<?php

namespace App\Http\Requests\Api\BaseRequest\Employee;

use Illuminate\Foundation\Http\FormRequest;
use JetBrains\PhpStorm\ArrayShape;
use JetBrains\PhpStorm\Pure;

class EmployeeUpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    #[ArrayShape(['rank' => "string", 'first_name' => "string", 'last_name' => "string", 'patronymic' => "string", 'phone_number' => "string", 'appointment_id' => "string", 'depency_id' => "string", 'organization_id' => "string", 'email' => "string"])] public function rules(): array
    {
        return [
            'rank' => 'integer|min:1|max:7',
            'first_name' => 'min:3|max:25|string',
            'last_name' => 'min:3|max:25|string',
            'patronymic' => 'string|min:3|max:20',
            'phone_number' => 'string',
            'appointment_id' => 'integer',
            'depency_id' => 'integer',
            'organization_id' => 'integer',
            'email' => 'email|unique:employees,email',
        ];
    }

    #[Pure] public function messages(): array
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
