<?php

namespace App\Http\Requests\Api\BaseRequest\Employee;

use Illuminate\Foundation\Http\FormRequest;

class EmployeeUpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'rank' => 'integer|min:1|max:7',
            'first_name' => 'min:3|max:25|string',
            'last_name' => 'min:3|max:25|string',
            'patronymic' => 'string|min:3|max:20',
            'phone_number' => 'string',
            'appointment_id' => 'integer',
            'depency_id' => 'integer',
            'organization_id' => 'integer',
            'email' => 'email|unique:employees,email',
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
