<?php

namespace App\Http\Requests\Api\BaseRequest\Employee;

use Illuminate\Foundation\Http\FormRequest;
use JetBrains\PhpStorm\ArrayShape;
use JetBrains\PhpStorm\Pure;

/**
 * @property mixed employee_id
 * @property mixed from_date
 * @property mixed to_date
 */
class EmployeeDefaultsRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    #[ArrayShape(['employee_id' => "string", 'reason_id' => "string", 'fromDate' => "string", 'toDate' => "string"])] public function rules(): array
    {
        return [
            'employee_id' => 'required',
            'reason_id' => 'required',
            'fromDate' => 'required|date',
            'toDate' => 'date',
        ];
    }

    #[Pure] public function messages(): array
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
