<?php

namespace App\Http\Requests\BaseRequest;

use App\Rules\BaseRule\RootRule;
use Illuminate\Foundation\Http\FormRequest;
use JetBrains\PhpStorm\ArrayShape;

class RoleRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    #[ArrayShape(['password' => "array", 'user_id' => "string[]", 'is_confirmed' => "string[]", 'is_admin' => "string[]", 'is_root' => "array"])]
    public function rules(): array
    {
        return [
            'password' => [
                'required',
                new RootRule,
            ],
            'is_confirmed' => [
                'boolean'
            ],
            'is_admin' => [
                'boolean'
            ],
            'is_root' => [

            ]
        ];
    }

    public function messages(): array
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
